// src/lib/countryCodes.ts

export const countryCodes = [
  { code: "+93", name: "Afghanistan", flag: "🇦🇫" },
  { code: "+355", name: "Albania", flag: "🇦🇱" },
  { code: "+213", name: "Algeria", flag: "🇩🇿" },
  { code: "+54", name: "Argentina", flag: "🇦🇷" },
  { code: "+61", name: "Australia", flag: "🇦🇺" },
  { code: "+43", name: "Austria", flag: "🇦🇹" },
  { code: "+880", name: "Bangladesh", flag: "🇧🇩" },
  { code: "+32", name: "Belgium", flag: "🇧🇪" },
  { code: "+55", name: "Brazil", flag: "🇧🇷" },
  { code: "+1", name: "Canada", flag: "🇨🇦" },
  { code: "+86", name: "China", flag: "🇨🇳" },
  { code: "+57", name: "Colombia", flag: "🇨🇴" },
  { code: "+45", name: "Denmark", flag: "🇩🇰" },
  { code: "+20", name: "Egypt", flag: "🇪🇬" },
  { code: "+33", name: "France", flag: "🇫🇷" },
  { code: "+49", name: "Germany", flag: "🇩🇪" },
  { code: "+30", name: "Greece", flag: "🇬🇷" },
  { code: "+852", name: "Hong Kong", flag: "🇭🇰" },
  { code: "+91", name: "India", flag: "🇮🇳" },
  { code: "+62", name: "Indonesia", flag: "🇮🇩" },
  { code: "+98", name: "Iran", flag: "🇮🇷" },
  { code: "+964", name: "Iraq", flag: "🇮🇶" },
  { code: "+353", name: "Ireland", flag: "🇮🇪" },
  { code: "+972", name: "Israel", flag: "🇮🇱" },
  { code: "+39", name: "Italy", flag: "🇮🇹" },
  { code: "+81", name: "Japan", flag: "🇯🇵" },
  { code: "+254", name: "Kenya", flag: "🇰🇪" },
  { code: "+60", name: "Malaysia", flag: "🇲🇾" },
  { code: "+52", name: "Mexico", flag: "🇲🇽" },
  { code: "+212", name: "Morocco", flag: "🇲🇦" },
  { code: "+95", name: "Myanmar", flag: "🇲🇲" },
  { code: "+977", name: "Nepal", flag: "🇳🇵" },
  { code: "+31", name: "Netherlands", flag: "🇳🇱" },
  { code: "+64", name: "New Zealand", flag: "🇳🇿" },
  { code: "+234", name: "Nigeria", flag: "🇳🇬" },
  { code: "+92", name: "Pakistan", flag: "🇵🇰" },
  { code: "+63", name: "Philippines", flag: "🇵🇭" },
  { code: "+48", name: "Poland", flag: "🇵🇱" },
  { code: "+351", name: "Portugal", flag: "🇵🇹" },
  { code: "+974", name: "Qatar", flag: "🇶🇦" },
  { code: "+7", name: "Russia", flag: "🇷🇺" },
  { code: "+966", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "+65", name: "Singapore", flag: "🇸🇬" },
  { code: "+27", name: "South Africa", flag: "🇿🇦" },
  { code: "+82", name: "South Korea", flag: "🇰🇷" },
  { code: "+34", name: "Spain", flag: "🇪🇸" },
  { code: "+94", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "+46", name: "Sweden", flag: "🇸🇪" },
  { code: "+41", name: "Switzerland", flag: "🇨🇭" },
  { code: "+66", name: "Thailand", flag: "🇹🇭" },
  { code: "+90", name: "Turkey", flag: "🇹🇷" },
  { code: "+380", name: "Ukraine", flag: "🇺🇦" },
  { code: "+971", name: "UAE", flag: "🇦🇪" },
  { code: "+44", name: "UK", flag: "🇬🇧" },
  { code: "+1", name: "USA", flag: "🇺🇸" },
  { code: "+84", name: "Vietnam", flag: "🇻🇳" },
  { code: "+967", name: "Yemen", flag: "🇾🇪" },
  { code: "+263", name: "Zimbabwe", flag: "🇿🇼" }
].sort((a, b) => a.name.localeCompare(b.name));